# Deploy dependencies first
apiVersion: skaffold/v2beta13
kind: Config
deploy:
  kubectl:
    manifests:
    - k8s/test-runner-account.yaml
  helm:
    releases:
      - name: redis
        remoteChart: redis
        repo: https://charts.bitnami.com/bitnami
        namespace: dev
        setValues:
          replica.replicaCount: 1
      - name: postgresql
        remoteChart: postgresql
        repo: https://charts.bitnami.com/bitnami
        namespace: dev
---
# Deploy services after
apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: robust-tjanst
build:
  artifacts:
  - image: netnodse/robust-web
    docker:
      dockerfile: Dockerfile.web
  - image: netnodse/robust-admin
    docker:
      dockerfile: Dockerfile.admin
  - image: netnodse/robust-test-runner
    docker:
      dockerfile: Dockerfile.tests
deploy:
  kubectl:
    defaultNamespace: dev
    manifests:
    - k8s/admin.yaml
    - k8s/web.yaml
    - k8s/tests.yaml
