apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-runner
  namespace: dev
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: test-runner
  namespace: tests
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "create", "delete"]
- apiGroups: [""]
  resources: ["pods/status", "pods/log"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: run-tests
  namespace: tests
subjects:
  - kind: ServiceAccount
    name: test-runner
    namespace: dev
roleRef:
  kind: Role
  name: test-runner
  apiGroup: rbac.authorization.k8s.io
