apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  ports:
    - port: 3000
  type: ClusterIP
  selector:
    app: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: netnodse/robust-web
          ports:
            - containerPort: 3000
          resources: {}
          env:
            - name: BASE_URL
              value: "http://robust.gcloud.netnod.se" 
            - name: REDIS_PASS
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: redis-password
            - name: REDIS_SERVER
              value: redis-master
            - name: REDIS_URL
              value: "redis://:$(REDIS_PASS)@$(REDIS_SERVER)"
            - name: SIGNED_COOKIE_KEYS
              valueFrom:
                secretKeyRef:
                  name: signed-cookie-keys
                  key: SIGNED_COOKIE_KEYS
            - name: NODE_ENV
              value: "development"
            - name: PGHOST
              value: postgresql
            - name: PGUSER
              value: postgres
            - name: PGDATABASE
              value: robust-tjanst
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: postgresql-password
            - name: DATABASE_URL
              value: "postgres://$(PGUSER):$(PGPASSWORD)@$(PGHOST)/$(PGDATABASE)"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik-public"
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  rules:
    - host: dev.robust.gcloud.netnod.se
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: web
                port:
                  number: 3000
  tls:
  - hosts:
    - dev.robust.gcloud.netnod.se
    secretName: dev-robust-gcloud-netnod-se-cert
